version: '3'
services:

  api:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    depends_on:
      - elasticsearch
    networks:
      - my-network
  
  kibana:
    image: kibana:7.17.9
    container_name: Kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my-network
  
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: Elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - my-network

networks:
  my-network:
